// auth
export const SIGN_USER = 'SIGN_USER';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_FAILURE = 'SIGN_USER_FAILURE';

export const SEND_AUTH_CODE = 'SEND_AUTH_CODE';
export const SEND_AUTH_CODE_SUCCESS = 'SEND_AUTH_CODE_SUCCESS';
export const SEND_AUTH_CODE_FAILURE = 'SEND_AUTH_CODE_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
